-- Last Update: 09.04.2020

local waterMountList = {
	"Azumarill Mount",
	"S Azumarill Mount",
	"Empoleon Mount",
	"S Empoleon Mount",
	"Whiscash Mount",
	"S Whiscash Mount",
	"Vaporeon Mount",
	"S Vaporeon Mount",
	"Mantine Mount",
	"S Mantine Mount",
	"Light Yellow Jet Skii",
	"Light Teal Jet Skii",
	"Light Red Jet Skii",
	"Light Purple Jet Skii",
	"Light Pink Jet Skii",
	"Light Orange Jet Skii",
	"Light Green Jet Skii",
	"Light Blue Jet Skii",
	"Swampert Mount",
	"S Swampert Mount",
	"Gyarados Mount",
	"S Gyarados Mount",
	"Dragonair Mount",
	"S Dragonair Mount",
	"Milotic Mount",
	"S Milotic Mount",
	"Sharpedo Mount",
	"S Sharpedo Mount",
	"Magikarp Mount",
	"S Magikarp Mount",
	"Lapras Mount",
	"S Lapras Mount",
	"Blastoise Mount",
	"S Blastoise Mount",
}

return waterMountList